# Generated by Django 4.0 on 2022-01-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
