# Generated by Django 4.0 on 2022-01-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=50)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=20)),
            ],
        ),
    ]
