# Generated by Django 4.0 on 2022-01-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='epoints',
            field=models.IntegerField(null=True),
        ),
    ]
